# Generated by Django 4.1.1 on 2022-09-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('telephone', models.IntegerField()),
                ('health', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appeal')),
            ],
        ),
        migrations.AddField(
            model_name='appeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.applicant'),
        ),
    ]
