# Generated by Django 4.1.1 on 2022-09-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appeal_options_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.applicant'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='appeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='core.appeal'),
        ),
    ]
