# Generated by Django 4.1.1 on 2022-09-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appeal_application_alter_emergency_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='dont_call',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='appeal',
            name='number_of_victims',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=30),
        ),
        migrations.AddField(
            model_name='applicant',
            name='image',
            field=models.ImageField(default='-', upload_to=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.IntegerField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health',
            field=models.CharField(blank=True, default='практически здоров', help_text='аллергоанамнез, хронические заболевания и т.д.', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
