# Generated by Django 4.1.1 on 2022-09-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appeal_dont_call_appeal_number_of_victims_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='name',
            field=models.CharField(choices=[('Полиция', 'Полиция'), ('Скорая', 'Скорая'), ('Пожарная', 'Пожарная')], max_length=30),
        ),
    ]
