# Generated by Django 4.1.1 on 2022-09-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_emergency_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ('date', 'number'), 'verbose_name': 'Appeal', 'verbose_name_plural': 'Appeals'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('name',), 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ('code',), 'verbose_name': 'Emergency', 'verbose_name_plural': 'Emergencies'},
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='appeal',
        ),
        migrations.AddField(
            model_name='appeal',
            name='emergency',
            field=models.ManyToManyField(related_name='Appeal', to='core.emergency'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appeal', to='core.applicant'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='dont_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health',
            field=models.CharField(blank=True, default='практически здоров', help_text='аллергоанамнез, хронические заболевания и т.д.', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='sex',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='M', max_length=255),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='name',
            field=models.CharField(choices=[('Полиция', 'Полиция'), ('Скорая', 'Скорая'), ('Пожарная', 'Пожарная')], max_length=255),
        ),
    ]
