# Generated by Django 4.1.1 on 2022-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appeal_options_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='name',
            field=models.CharField(choices=[('Полиция', 'Полиция'), ('Скорая', 'Скорая'), ('Пожарная', 'Пожарная')], max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='telephone',
            field=models.IntegerField(verbose_name='Номер телефона'),
        ),
    ]
