# Generated by Django 4.1.1 on 2022-09-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_sex_applicant_gender_alter_applicant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужчина'), ('Ж', 'Женщина')], default='M', max_length=255, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='health',
            field=models.CharField(blank=True, default='практически здоров', help_text='аллергоанамнез, хронические заболевания и т.д.', max_length=255, verbose_name='Состояние здоровья'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='image',
            field=models.ImageField(default='-', upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер телефона'),
        ),
    ]
