# Generated by Django 4.1.1 on 2022-09-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_applicant_birth_alter_applicant_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Appeal', to='core.applicant', verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='dont_call',
            field=models.BooleanField(default=False, verbose_name='Не звонить?'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='emergency',
            field=models.ManyToManyField(related_name='Appeal', to='core.emergency', verbose_name='Экстренная служба'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.IntegerField(db_index=True, editable=False, unique=True, verbose_name='Номер обращения'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='number_of_victims',
            field=models.IntegerField(default=0, verbose_name='Количество обращений'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('В работе', 'В работе'), ('Завершено', 'Завершено')], default='В работе', max_length=255, verbose_name='Статус'),
        ),
    ]
