# Generated by Django 4.0.5 on 2022-09-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_appeal_application_alter_appeal_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Код'),
        ),
    ]
