# Generated by Django 4.0.5 on 2022-09-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_emergency_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ('date', 'number'), 'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('name',), 'verbose_name': 'Заявитель', 'verbose_name_plural': 'Заявители'},
        ),
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ('code',), 'verbose_name': 'Экстренная служба', 'verbose_name_plural': 'Экстренные службы'},
        ),
    ]
