# Generated by Django 4.1.1 on 2022-09-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appeal_options_alter_applicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='number',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Номер обращения'),
        ),
    ]
